### ISSUE TITLE
ci: sudo command not found

### ISSUE THREAD

**Issue by j1mbo64** [rnbguy/aur-maintainer#3]
Hello, in your CI there is this message : `auto-updater.sh: line 59: sudo -u pasudo: command not found`

Here : https://github.com/rnbguy/aur-maintainer/blob/382e63243ee906020a3a9d0b86cc37142328b7cf/auto-updater.sh#L59C1-L59C15

So the packages are not updated, can you check ?

**Comment by rnbguy** [comment]
Thanks for reporting :pray: It should work now :tada:
